En-Luna/ViewModels/Documents/DocumentEditViewModel.cs
namespace En_Luna.ViewModels
{
    public class DocumentEditViewModel
    {
        public int Id { get; set; }

        // todo other editable properties
    }
}

En-Luna/ViewModels/Documents/DocumentIndexViewModel.cs
using X.PagedList;

namespace En_Luna.ViewModels
{
    public class DocumentIndexViewModel
    {
        public IPagedList<DocumentViewModel> Documents { get; set; }
    }
}

En-Luna/ViewModels/Documents/DocumentViewModel.cs
namespace En_Luna.ViewModels
{
    public class DocumentViewModel
    {
        public int Id { get; set; }
        public string Content { get; set; } = string.Empty;
        public int AccountId { get; set; }
        public bool IsVerified { get; set; }

        //todo will need related account
    }
}

En-Luna/Areas/Admin/Controllers/DocumentsController.cs
using AutoMapper;
using En_Luna.Data.Models;
using En_Luna.Data.Services;
using En_Luna.Extensions;
using En_Luna.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using X.PagedList;

namespace Jobbie.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DocumentsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IDocumentService _documentService;

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentsController"/> class.
        /// </summary>
        /// <param name="mapper"></param>
        /// <param name="service"></param>
        public DocumentsController(IMapper mapper, IDocumentService service)
        {
            _mapper = mapper;
            _documentService = service;
        }

        /// <summary>
        /// Indexes the specified page.
        /// </summary>
        /// <param name="page">The page.</param>
        /// <returns></returns>
        public IActionResult Index(int? page)
        {
            IEnumerable<Document> documents = _documentService.List();

            IPagedList<DocumentViewModel> documentViewModels = documents
                .ToPagedList(page ?? 1, En_Luna.Constants.Constants.PageSize)
                .Map<Document, DocumentViewModel>(_mapper);

            DocumentIndexViewModel model = new DocumentIndexViewModel
            {
                Documents = documentViewModels
            };

            return View(model);
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public IActionResult Edit(int? id)
        {
            Document? document = id.HasValue
                ? _documentService.Get(x => x.Id == id.Value)
                : new Document();

            if (document == null)
            {
                return RedirectToAction("Index");
            }

            DocumentEditViewModel model = _mapper.Map<DocumentEditViewModel>(document);

            return View(model);
        }

        /// <summary>
        /// Edits the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(DocumentEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                //InstantiateSelectLists(model);
                return View(model);
            }

            if (model.Id != 0)
            {
                Document? document = _documentService.Get(x => x.Id == model.Id);
                _mapper.Map(model, document);
                _documentService.Update(document);
            }
            else
            {
                Document document = _mapper.Map<Document>(model);
                _documentService.Create(document);
            }

            return RedirectToAction("Index");
        }

        public JsonResult Approve(int id)
        {
            Document? document = _documentService.Get(x => x.Id == id);

            if (document == null)
            {
                return Json(false);
            }

            _documentService.Approve(document);

            // todo notify user

            return Json(true);
        }

        public JsonResult Deny(int id)
        {
            Document? document = _documentService.Get(x => x.Id == id);

            if (document == null)
            {
                return Json(false);
            }

            _documentService.Deny(document);

            // todo notify user

            return Json(true);
        }

        public JsonResult Delete(int id)
        {
            Document? document = _documentService.Get(x => x.Id == id);

            if (document == null)
            {
                return Json(false);
            }

            _documentService.Delete(document);

            return Json(true);
        }
    }
}

En-Luna/Areas/Admin/Views/Documents/Index.cshtml
@using X.PagedList.Mvc.Core
@using En_Luna.ViewModels

@model DocumentIndexViewModel

<div class="row mt-4">
    <div class="col">
        <h2>Documents</h2>
        <hr />
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <a class="btn btn-primary" asp-area="Admin" asp-controller="Documents" asp-action="Edit">New</a>
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <h4>Current Documents</h4>
    </div>
</div>
<!--TODO Filters-->

<div class="row mt-2">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">TODO</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (DocumentViewModel item in Model.Documents)
                {
                    <tr>
                        <td>TODO</td>
                        <td>
                            <a href="/Admin/Documents/Edit/@item.Id" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <a href="javascript:void(0);" class="btn btn-danger" onclick="verify('/Admin/Documents/Verify', @item.Id, this)">Verify</a>
                        </td>
                        <td>
                            <a href="javascript:void(0);" class="btn btn-danger" onclick="softDelete('/Admin/Documents/Delete', @item.Id, this)">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.PagedListPager(Model.Documents, page => Url.Action("Index", new { page }), En_Luna.Helpers.HtmlHelper.PagedListRenderOptions)
    </div>
</div>