En-Luna/ViewModels/Licenses/LicenseEditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace En_Luna.ViewModels
{
    public class LicenseEditViewModel
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("Contractor")]
        public int ContractorId { get; set; }
        public SelectList? Contractors { get; set; }

        [Required]
        [DisplayName("State")]
        public int StateId { get; set; }
        public SelectList? States { get; set; }

        public string Name { get; set; } = string.Empty;
        public int Level { get; set; }

        [DisplayName("Verified?")]
        public bool IsVerified { get; set; }

        [Required]
        [DisplayName("License Number")]
        public string LicenseNumber { get; set; } = string.Empty;
    }
}

En-Luna/ViewModels/Licenses/LicenseIndexViewModel.cs
using X.PagedList;

namespace En_Luna.ViewModels
{
    public class LicenseIndexViewModel
    {
        public IPagedList<LicenseViewModel> Licenses { get; set; }
    }
}

En-Luna/ViewModels/Licenses/LicenseViewModel.cs
namespace En_Luna.ViewModels
{
    public class LicenseViewModel
    {
        public int Id { get; set; }
        public int ContractorId { get; set; }
        public int StateId { get; set; }
        public string Name { get; set; } = string.Empty;
        public int Level { get; set; }
        public bool IsVerified { get; set; }
        public string LicenseNumber { get; set; } = string.Empty;
        public ContractorViewModel? Contractor { get; set; }
        public StateViewModel? State { get; set; }
    }
}

En-Luna/Areas/Admin/Controllers/LicensesController.cs
using AutoMapper;
using En_Luna.Data.Models;
using En_Luna.Data.Services;
using En_Luna.Extensions;
using En_Luna.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using X.PagedList;

namespace Jobbie.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class LicensesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly ILicenseService _licenseService;
        private readonly IStateService _stateService;

        /// <summary>
        /// Initializes a new instance of the <see cref="LicensesController"/> class.
        /// </summary>
        /// <param name="mapper">The mapper.</param>
        /// <param name="userService">The account service.</param>
        /// <param name="service">The service.</param>
        /// <param name="stateService">The state service.</param>
        public LicensesController(IMapper mapper, IUserService userService, 
            ILicenseService service, IStateService stateService)
        {
            _mapper = mapper;
            _userService = userService;
            _licenseService = service;
            _stateService = stateService;
        }

        /// <summary>
        /// Indexes the specified page.
        /// </summary>
        /// <param name="page">The page.</param>
        /// <returns></returns>
        public IActionResult Index(int? page)
        {
            IEnumerable<License> licenses = _licenseService.List();

            IPagedList<LicenseViewModel> licenseViewModels = licenses
                .ToPagedList(page ?? 1, En_Luna.Constants.Constants.PageSize)
                .Map<License, LicenseViewModel>(_mapper);

            LicenseIndexViewModel model = new LicenseIndexViewModel
            {
                Licenses = licenseViewModels
            };

            return View(model);
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public IActionResult Edit(int? id)
        {
            License? license = id.HasValue
                ? _licenseService.Get(x => x.Id == id.Value)
                : new License();

            if (license == null)
            {
                return RedirectToAction("Index");
            }

            LicenseEditViewModel model = _mapper.Map<LicenseEditViewModel>(license);
            InstantiateSelectLists(model);

            return View(model);
        }

        /// <summary>
        /// Edits the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(LicenseEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                InstantiateSelectLists(model);
                return View(model);
            }

            if (model.Id != 0)
            {
                License? license = _licenseService.Get(x => x.Id == model.Id);
                _mapper.Map(model, license);
                _licenseService.Update(license);
            }
            else
            {
                License license = _mapper.Map<License>(model);
                _licenseService.Create(license);
            }

            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            License? license = _licenseService.Get(x => x.Id == id);

            if (license == null)
            {
                return Json(false);
            }

            _licenseService.Delete(license);

            return Json(true);
        }

        public JsonResult Verify(int id)
        {
            License? license = _licenseService.Get(x => x.Id == id);

            if (license == null)
            {
                return Json(false);
            }

            _licenseService.Verify(license);

            return Json(true);
        }

        private void InstantiateSelectLists(LicenseEditViewModel model)
        {
            model.Contractors = new SelectList(
                _userService
                .List()
                .OrderBy(x => x.LastName).ThenBy(x => x.FirstName)
                .Select(
                    x => new { x.ContractorId, Name = $"{x.LastName}, {x.FirstName}"}), 
                "ContractorId", 
                "Name", 
                model.ContractorId
            );

            model.States = new SelectList(_stateService.List(), "Id", "Name", model.StateId);
        }
    }
}

En-Luna/Areas/Admin/Views/Licenses/Edit.cshtml
@using En_Luna.ViewModels;

@model LicenseEditViewModel
@{
    ViewData["Title"] = "Edit License";
}
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h2>License</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="row">
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(model => model.ContractorId, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.ContractorId, Model.Contractors, En_Luna.Constants.Constants.EmptySelectOptionText, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ContractorId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.StateId, Model.States, En_Luna.Constants.Constants.EmptySelectOptionText, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(model => model.LicenseNumber, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.LicenseNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LicenseNumber, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(model => model.Level, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Level, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Level, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    @Html.CheckBoxFor(model => model.IsVerified, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.LabelFor(model => model.IsVerified, htmlAttributes: new { @class = "control-label" })
                    @Html.ValidationMessageFor(model => model.IsVerified, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Licenses" asp-action="Index">Cancel</a>
                </div>
            </div>
        </div>
    </div>
}

En-Luna/Areas/Admin/Views/Licenses/Index.cshtml
@using X.PagedList.Mvc.Core
@using En_Luna.ViewModels

@model LicenseIndexViewModel

<div class="row mt-4">
    <div class="col">
        <h2>Licenses</h2>
        <hr />
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <a class="btn btn-primary" asp-area="Admin" asp-controller="Licenses" asp-action="Edit">New</a>
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <h4>Current Licenses</h4>
    </div>
</div>
<!--TODO Filters-->

<div class="row mt-2">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (LicenseViewModel item in Model.Licenses)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>
                            <a href="/Admin/Licenses/Edit/@item.Id" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <a href="javascript:void(0);" class="btn btn-danger" onclick="softDelete('/Admin/Licenses/Delete', @item.Id, this)">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.PagedListPager(Model.Licenses, page => Url.Action("Index", new { page }), En_Luna.Helpers.HtmlHelper.PagedListRenderOptions)
    </div>
</div>