En-Luna/ViewModels/CompanyTypes/CompanyTypeEditViewModel.cs
namespace En_Luna.ViewModels
{
    public class CompanyTypeEditViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }
}

En-Luna/ViewModels/CompanyTypes/CompanyTypeIndexViewModel.cs
using X.PagedList;

namespace En_Luna.ViewModels
{
    public class CompanyTypeIndexViewModel
    {
        public IPagedList<CompanyTypeViewModel> CompanyTypes { get; set; }
    }
}

En-Luna/ViewModels/CompanyTypes/CompanyTypeViewModel.cs
namespace En_Luna.ViewModels
{
    public class CompanyTypeViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }
}

En-Luna/Areas/Admin/Controllers/CompanyTypesController.cs
using AutoMapper;
using En_Luna.Data.Models;
using En_Luna.Data.Services;
using En_Luna.Extensions;
using En_Luna.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using X.PagedList;

namespace Jobbie.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CompanyTypesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ICompanyTypeService _companyTypeService;

        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyTypesController"/> class.
        /// </summary>
        /// <param name="mapper"></param>
        /// <param name="companyTypeService"></param>
        public CompanyTypesController(IMapper mapper, ICompanyTypeService companyTypeService)
        {
            _mapper = mapper;
            _companyTypeService = companyTypeService;
        }

        /// <summary>
        /// Indexes the specified page.
        /// </summary>
        /// <param name="page">The page.</param>
        /// <returns></returns>
        public IActionResult Index(int? page)
        {
            IEnumerable<CompanyType> companyTypes = _companyTypeService.List();

            IPagedList<CompanyTypeViewModel> companyTypeViewModels = companyTypes
                .ToPagedList(page ?? 1, En_Luna.Constants.Constants.PageSize)
                .Map<CompanyType, CompanyTypeViewModel>(_mapper);

            CompanyTypeIndexViewModel model = new CompanyTypeIndexViewModel
            {
                CompanyTypes = companyTypeViewModels
            };

            return View(model);
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public IActionResult Edit(int? id)
        {
            CompanyType? companyType = id.HasValue
                ? _companyTypeService.Get(x => x.Id == id.Value)
                : new CompanyType();

            if (companyType == null)
            {
                return RedirectToAction("Index");
            }

            CompanyTypeEditViewModel model = _mapper.Map<CompanyTypeEditViewModel>(companyType);

            return View(model);
        }

        /// <summary>
        /// Edits the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(CompanyTypeEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                //InstantiateSelectLists(model);
                return View(model);
            }

            if (model.Id != 0)
            {
                CompanyType? companyType = _companyTypeService.Get(x => x.Id == model.Id);
                _mapper.Map(model, companyType);
                _companyTypeService.Update(companyType);
            }
            else
            {
                CompanyType companyType = _mapper.Map<CompanyType>(model);
                _companyTypeService.Create(companyType);
            }

            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            CompanyType? companyType = _companyTypeService.Get(x => x.Id == id);

            if (companyType == null)
            {
                return Json(false);
            }

            _companyTypeService.Delete(companyType);

            return Json(true);
        }
    }
}

En-Luna/Areas/Admin/Views/CompanyTypes/Edit.cshtml
@using En_Luna.ViewModels;

@model CompanyTypeEditViewModel
@{
    ViewData["Title"] = "Edit Company Type";
}
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h2>Company Type</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="row">
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a class="btn btn-primary" asp-area="Admin" asp-controller="CompanyTypes" asp-action="Index">Cancel</a>
                </div>
            </div>
        </div>
    </div>
}

En-Luna/Areas/Admin/Views/CompanyTypes/Index.cshtml
@using X.PagedList.Mvc.Core
@using En_Luna.ViewModels

@model CompanyTypeIndexViewModel

<div class="row mt-4">
    <div class="col">
        <h2>Company Types</h2>
        <hr />
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <a class="btn btn-primary" asp-area="Admin" asp-controller="CompanyTypes" asp-action="Edit">New</a>
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <h4>Current Company Types</h4>
    </div>
</div>
<!--TODO Filters-->

<div class="row mt-2">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (CompanyTypeViewModel item in Model.CompanyTypes)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>
                            <a href="/Admin/CompanyTypes/Edit/@item.Id" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <a href="javascript:void(0);" class="btn btn-danger" onclick="softDelete('/Admin/CompanyTypes/Delete', @item.Id, this)">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.PagedListPager(Model.CompanyTypes, page => Url.Action("Index", new { page }), En_Luna.Helpers.HtmlHelper.PagedListRenderOptions)
    </div>
</div>