En-Luna/ViewModels/Specialties/SpecialtyEditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;

namespace En_Luna.ViewModels
{
    public class SpecialtyEditViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;

        [DisplayName("Expertise")]
        public int ExpertiseId { get; set; }
        public SelectList? Expertises { get; set; }
    }
}

En-Luna/ViewModels/Specialties/SpecialtyIndexViewModel.cs
using X.PagedList;

namespace En_Luna.ViewModels
{
    public class SpecialtyIndexViewModel
    {
        public IPagedList<SpecialtyViewModel> Specialties { get; set; }
    }
}

En-Luna/ViewModels/Specialties/SpecialtyViewModel.cs
namespace En_Luna.ViewModels
{
    public class SpecialtyViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public int ExpertiseId { get; set; }
        public ExpertiseViewModel? Expertise { get; set; }
    }
}

En-Luna/Areas/Admin/Controllers/SpecialtiesController.cs
using AutoMapper;
using En_Luna.Data.Models;
using En_Luna.Data.Services;
using En_Luna.Extensions;
using En_Luna.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using X.PagedList;

namespace Jobbie.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SpecialtiesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IExpertiseService _expertiseService;
        private readonly ISpecialtyService _specialtyService;

        /// <summary>
        /// Initializes a new instance of the <see cref="SpecialtiesController"/> class.
        /// </summary>
        /// <param name="mapper">The mapper.</param>
        /// <param name="service">The service.</param>
        /// <param name="expertiseService">The expertise service.</param>
        public SpecialtiesController(IMapper mapper, ISpecialtyService service, IExpertiseService expertiseService)
        {
            _mapper = mapper;
            _specialtyService = service;
            _expertiseService = expertiseService;
        }

        /// <summary>
        /// Indexes the specified page.
        /// </summary>
        /// <param name="page">The page.</param>
        /// <returns></returns>
        public IActionResult Index(int? page)
        {
            IEnumerable<Specialty> specialtys = _specialtyService.List();

            IPagedList<SpecialtyViewModel> specialtyViewModels = specialtys
                .ToPagedList(page ?? 1, En_Luna.Constants.Constants.PageSize)
                .Map<Specialty, SpecialtyViewModel>(_mapper);

            SpecialtyIndexViewModel model = new SpecialtyIndexViewModel
            {
                Specialties = specialtyViewModels
            };

            return View(model);
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public IActionResult Edit(int? id)
        {
            Specialty? specialty = id.HasValue
                ? _specialtyService.Get(x => x.Id == id.Value)
                : new Specialty();

            if (specialty == null)
            {
                return RedirectToAction("Index");
            }

            SpecialtyEditViewModel model = _mapper.Map<SpecialtyEditViewModel>(specialty);
            InstantiateSelectLists(model);

            return View(model);
        }

        /// <summary>
        /// Edits the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(SpecialtyEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                InstantiateSelectLists(model);
                return View(model);
            }

            if (model.Id != 0)
            {
                Specialty? specialty = _specialtyService.Get(x => x.Id == model.Id);
                _mapper.Map(model, specialty);
                _specialtyService.Update(specialty);
            }
            else
            {
                Specialty specialty = _mapper.Map<Specialty>(model);
                _specialtyService.Create(specialty);
            }

            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            Specialty? specialty = _specialtyService.Get(x => x.Id == id);

            if (specialty == null)
            {
                return Json(false);
            }

            _specialtyService.Delete(specialty);

            return Json(true);
        }

        private void InstantiateSelectLists(SpecialtyEditViewModel model)
        {
            model.Expertises = new SelectList(_expertiseService.List(), "Id", "Name", model.ExpertiseId);
        }
    }
}

En-Luna/Areas/Admin/Views/Specialties/Edit.cshtml
@using En_Luna.ViewModels;

@model SpecialtyEditViewModel
@{
    ViewData["Title"] = "Edit Specialty";
}
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h2>Specialty</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="row">
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(model => model.ExpertiseId, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.ExpertiseId, Model.Expertises, En_Luna.Constants.Constants.EmptySelectOptionText, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ExpertiseId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Specialties" asp-action="Index">Cancel</a>
                </div>
            </div>
        </div>
    </div>
}

En-Luna/Areas/Admin/Views/Specialties/Index.cshtml
@using X.PagedList.Mvc.Core
@using En_Luna.ViewModels

@model SpecialtyIndexViewModel

<div class="row mt-4">
    <div class="col">
        <h2>Specialties</h2>
        <hr />
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <a class="btn btn-primary" asp-area="Admin" asp-controller="Specialties" asp-action="Edit">New</a>
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <h4>Current Specialties</h4>
    </div>
</div>

<!--TODO Filters-->

<div class="row mt-2">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (SpecialtyViewModel item in Model.Specialties)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>
                            <a href="/Admin/Specialties/Edit/@item.Id" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <a href="javascript:void(0);" class="btn btn-danger" onclick="softDelete('/Admin/Specialties/Delete', @item.Id, this)">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.PagedListPager(Model.Specialties, page => Url.Action("Index", new { page }), En_Luna.Helpers.HtmlHelper.PagedListRenderOptions)
    </div>
</div>